### PR TITLE
Updated all libraries and used latest clamav engine

### PR DESCRIPTION
**Pull request by muthuka**
- Added latest libraries in package.json
- Upgraded clamav in docker-compose
- Using Dockerfile inside docker-compose
- Updated version to v1.4.1

### CODE REVIEW

**Comment by muthuka** [comment]
@benzino77 Updated all dependbot issues with this PR

**Comment by benzino77** [comment]
Thanks! Will have a look at it after the weekend.

**Comment by benzino77** [comment]
Thanks Muthu for your contribution!

Can you please split your PR? One for correcting spelling another one for changing Node version, etc.

**Comment by muthuka** [comment]
That’s great. I updated this PR with README reverted.

Good work. I am trying to make this open source application accessible across my organization. I will do another PR little later.

Regards,

Muthu Arumugam
***@***.***

**Comment by benzino77** [comment]
Thanks a lot: https://github.com/benzino77/clamav-rest-api/releases/tag/v1.5.0

**Pull request closed without merging**
